/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/actividad2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1, 0, 0]} scale={[0.615, 0.823, 0.615]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials.suelo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials.piso}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        position={[4.737, 5.225, -1.441]}
        rotation={[-0.403, -0.147, 0.093]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['hojas.001']}
        position={[1.854, 7.413, -1.058]}
        rotation={[-2.695, -0.982, -2.198]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.hojas}
        position={[2.995, 4.16, 8.578]}
        rotation={[-2.491, -0.876, -2.457]}
        scale={0.625}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials['hojas.001']}
        position={[3.523, 5.528, 6.837]}
        rotation={[-2.73, 0.928, -2.912]}
        scale={0.625}
      />
    </group>
  )
}

useGLTF.preload('/actividad2.glb')
